/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Test } from './types';

const rawTests: Array<[string, string, string, number, string?, string?]> = [
  // Mandatory Routine Pathology Tests (Arogya Series Core)
  ['t-cbc-exact', 'Complete Blood Count (CBC)', 'Hematology & Blood Tests', 250, 'Blood', '12 hours'],
  ['t-malaria-exact', 'Malaria Test', 'Infectious Diseases', 200, 'Blood', '12 hours'],
  ['t-crp-exact', 'C-Reactive Protein (CRP)', 'Inflammatory Markers', 300, 'Blood', '12 hours'],
  ['t-thyroid-exact', 'Thyroid Profile', 'Hormone & Thyroid Tests', 400, 'Blood', '12 hours'],
  ['t-stool-ph-exact', 'Stool Routine & pH', 'Stool Tests', 150, 'Stool', '12 hours'],
  ['t-stool-culture-exact', 'Stool Culture Test', 'Stool Tests', 500, 'Stool', '24 hours'],
  ['t-throat-swab-exact', 'Throat Swab Culture', 'Culture & Microbiology', 600, 'Throat Swab', '24 hours'],
  ['t-nasal-swab-exact', 'Nasal Swab Culture', 'Culture & Microbiology', 800, 'Nasal Swab', '24 hours'],
  ['t-sars-cov2-exact', 'SARS CoV-2 RT-PCR', 'COVID & Viral Tests', 500, 'Nasal Swab', '12 hours'],
  ['t-pleural-fluid-exact', 'Pleural Fluid Analysis', 'Fluid Investigations', 1000, 'Pleural Fluid', '24 hours'],
  ['t-toxoplasma-igm-exact', 'Toxoplasma (IgM) Test', 'Pregnancy Tests', 1000, 'Blood', '24 hours'],

  // Page 1
  ['t-fsh-lh-prolactin', 'FSH, LH, PROLACTIN', 'Hormone Tests', 1700, 'Blood', '24 hours'],
  ['t-17-oh-progesterone', '17 OH PROGESTERONE', 'Hormone Tests', 550, 'Blood', '24 hours'],
  ['t-24h-urine-protein', '24 HOURS URINE PROTEIN', 'Urine Tests', 428, 'Urine', '24 hours'],
  ['t-25-oh-vitamin-d', '25-OH VITAMIN D', 'Vitamin Tests', 800, 'Blood', '24 hours'],
  ['t-25-oh-vitamin-d3', '25-OH VITAMIN D3', 'Vitamin Tests', 800, 'Blood', '24 hours'],
  ['t-achr-antibodies', 'AChR Antibodies Acetyl Choline Receptor Antibodies Serum', 'Autoimmune Tests', 3400, 'Blood', '48 hours'],
  ['t-aptt', 'ACTIVATED PARTIAL THROMBIN TIME (APTT)', 'Blood Tests', 480, 'Blood', '24 hours'],
  ['t-ada', 'ADENOSINE DEAMINASE (ADA)', 'Infection & Fever Tests', 855, 'Fluid/Serum', '24 hours'],
  ['t-acth', 'ADRENOCORTICOTROPIC HORMONE (ACTH)', 'Hormone Tests', 1500, 'Blood', '24 hours'],
  ['t-afb-stain', 'AFB STAIN FOR ANY SMEAR', 'Culture & Microbiology', 350, 'Sputum/Swab', '24 hours'],
  ['t-albumin', 'ALBUMIN', 'Liver Function Tests', 200, 'Blood', '24 hours'],
  ['t-alcohol-screen', 'ALCOHOL (ETHANOL) SCREEN', 'Miscellaneous Tests', 1520, 'Blood', '24 hours'],
  ['t-alp', 'ALKALINE PHOSPHATASE (ALP)', 'Liver Function Tests', 200, 'Blood', '24 hours'],
  ['t-allergy-profile', 'ALLERGY PROFILE', 'Allergy Tests', 4500, 'Blood', '48 hours'],
  ['t-allergy-skin', 'ALLERGY PROFILE ( SKIN CONTACT )', 'Allergy Tests', 3500, 'Skin', '24 hours'],
  ['t-allergy-food', 'ALLERGY PROFILE FOOD', 'Allergy Tests', 4500, 'Blood', '48 hours'],
  ['t-afp', 'ALPHA FETO PROTEIN (AFP)', 'Cancer Marker Tests', 850, 'Blood', '24 hours'],
  ['t-ama', 'AMA', 'Autoimmune Tests', 650, 'Blood', '24 hours'],
  ['t-ammonia', 'AMMONIA', 'Miscellaneous Tests', 900, 'Blood', '24 hours'],
  ['t-amylase', 'AMYLASE', 'Miscellaneous Tests', 550, 'Blood', '24 hours'],
  ['t-amylase-csf', 'AMYLASE (CSF)', 'Miscellaneous Tests', 665, 'CSF Fluid', '24 hours'],
  ['t-ana-blot', 'ANA BLOT 17 ANTIGEN', 'Autoimmune Tests', 3400, 'Blood', '48 hours'],
  ['t-ana-ifa', 'ANA by IFA', 'Autoimmune Tests', 950, 'Blood', '24 hours'],
  ['t-ana-hep2', 'ANA HEP 2 METHOD', 'Autoimmune Tests', 950, 'Blood', '24 hours'],
  ['t-ana-profile', 'ANA PROFILE', 'Autoimmune Tests', 5000, 'Blood', '48 hours'],
  ['t-ana-quant', 'ANA QUANTITATIVE', 'Autoimmune Tests', 600, 'Blood', '24 hours'],
  ['t-anca', 'ANCA', 'Autoimmune Tests', 1140, 'Blood', '48 hours'],
  ['t-ace', 'angiotensin-converting enzyme (ACE)', 'Miscellaneous Tests', 1000, 'Blood', '24 hours'],
  ['t-anti-cardiolipin-igg', 'ANTI CARDIOLIPIN ANTIBODY IgG', 'Autoimmune Tests', 800, 'Blood', '24 hours'],

  // Page 2
  ['t-anti-cardiolipin-igm', 'ANTI CARDIOLIPIN ANTIBODY IgM', 'Autoimmune Tests', 800, 'Blood', '24 hours'],
  ['t-anti-cardiolipin-iga', 'ANTI CARDIOLIPIN ANTIBODY-IgA', 'Autoimmune Tests', 732, 'Blood', '24 hours'],
  ['t-anti-ccp', 'ANTI CCP ANTIBODY', 'Autoimmune Tests', 1200, 'Blood', '24 hours'],
  ['t-anti-gliadin-iga', 'ANTI GLIADIN ANTIBODY IGA', 'Autoimmune Tests', 1700, 'Blood', '24 hours'],
  ['t-anti-hav-igm', 'ANTI HAV IgM', 'Infection & Fever Tests', 855, 'Blood', '24 hours'],
  ['t-anti-hbc-igg', 'ANTI HBC IgG', 'Infection & Fever Tests', 855, 'Blood', '24 hours'],
  ['t-anti-hbc-igm', 'ANTI HBC IgM', 'Infection & Fever Tests', 855, 'Blood', '24 hours'],
  ['t-anti-hbs', 'ANTI HBs ANTIBODY', 'Infection & Fever Tests', 808, 'Blood', '24 hours'],
  ['t-anti-hcv', 'ANTI HCV', 'Infection & Fever Tests', 700, 'Blood', '24 hours'],
  ['t-anti-hcv-screening', 'ANTI HCV (SCREENING)', 'Infection & Fever Tests', 665, 'Blood', '24 hours'],
  ['t-anti-hev-igm', 'ANTI HEV IgM', 'Infection & Fever Tests', 1425, 'Blood', '24 hours'],
  ['t-amh', 'ANTI MULLERIAN HORMONE (AMH)', 'Hormone Tests', 1900, 'Blood', '24 hours'],
  ['t-anti-musk', 'Anti Musk Antibodies', 'Autoimmune Tests', 6500, 'Blood', '48 hours'],
  ['t-anti-phospholipid-igg', 'ANTI PHOSPHOLIPID ANTIBODY IgG', 'Autoimmune Tests', 855, 'Blood', '24 hours'],
  ['t-anti-phospholipid-igm', 'ANTI PHOSPHOLIPID ANTIBODY IgM', 'Autoimmune Tests', 855, 'Blood', '24 hours'],
  ['t-anti-ssa-ro', 'Anti SS-A(RO)ANTIBODY', 'Autoimmune Tests', 1000, 'Blood', '24 hours'],
  ['t-anti-ssb-la', 'Anti SS-B(LA) Antibody', 'Autoimmune Tests', 1000, 'Blood', '24 hours'],
  ['t-anti-ttg-igg', 'ANTI T.T.G - IgG', 'Autoimmune Tests', 1900, 'Blood', '24 hours'],
  ['t-anti-thyroglobulin', 'ANTI THYROGLOBULIN ANTIBODY', 'Thyroid Tests', 1425, 'Blood', '24 hours'],
  ['t-anti-tg', 'ANTI THYROGLOBULIN ANTIBODY (ANTI-TG)', 'Thyroid Tests', 1520, 'Blood', '24 hours'],
  ['t-anti-tpo-ata', 'ANTI THYROID ANTIBODIES(TPO ATA)', 'Thyroid Tests', 1568, 'Blood', '24 hours'],
  ['t-anti-ttg-iga', 'ANTI TTG IGA', 'Autoimmune Tests', 1900, 'Blood', '24 hours'],
  ['t-anti-dsdna', 'Anti-dsDNA', 'Autoimmune Tests', 800, 'Blood', '24 hours'],
  ['t-apla-profile', 'ANTIPHOSPHOLIPID ANTIBODY PROFILE (APLA PROFILE)', 'Autoimmune Tests', 1900, 'Blood', '24 hours'],
  ['t-apolipoproteins', 'APOLIPOPROTEINS A1 AND B', 'Cardiac Tests', 1330, 'Blood', '24 hours'],
  ['t-arogya-a', 'Arogya A', 'Miscellaneous Tests', 899, 'Blood/Urine', '24 hours'],
  ['t-arogya-d', 'Arogya D', 'Miscellaneous Tests', 2500, 'Blood/Urine', '24 hours'],
  ['t-arogya-e', 'Arogya E CARDIAC PROFILE', 'Cardiac Tests', 2500, 'Blood', '24 hours'],

  // Page 3
  ['t-arogyam-b', 'arogyam B', 'Miscellaneous Tests', 1000, 'Blood', '24 hours'],
  ['t-arogyam-c', 'arogyam C', 'Miscellaneous Tests', 2000, 'Blood', '24 hours'],
  ['t-abg', 'ARTERIAL BLOOD GASES (ABG)', 'Blood Tests', 1900, 'Arterial Blood', '12 hours'],
  ['t-aso-qual', 'ASO-TITRE (QUALITATIVE)', 'Infection & Fever Tests', 570, 'Blood', '24 hours'],
  ['t-aso-quant', 'ASO-TITRE (QUANTITATIVE)', 'Infection & Fever Tests', 665, 'Blood', '24 hours'],
  ['t-aspergillus-ige', 'Aspergillus fumingatus ige', 'Allergy Tests', 1800, 'Blood', '24 hours'],
  ['t-atg', 'ATG', 'Thyroid Tests', 700, 'Blood', '24 hours'],
  ['t-bence-jones', 'BENCE JONES PROTEIN', 'Urine Tests', 1425, 'Urine', '24 hours'],
  ['t-beta2-gp1-igg', 'Beta 2 Gp 1 IGG', 'Autoimmune Tests', 2500, 'Blood', '24 hours'],
  ['t-beta2-gp1-igm', 'Beta 2 Gp1 IGM', 'Autoimmune Tests', 2500, 'Blood', '24 hours'],
  ['t-beta2-micro', 'Beta 2 Microglobulin', 'Cancer Marker Tests', 1890, 'Blood', '24 hours'],
  ['t-beta-hcg', 'BETA HCG TOTAL SERUM', 'Pregnancy Tests', 650, 'Blood', '24 hours'],
  ['t-bicarbonate', 'BICARBONATE (HCO3)', 'Kidney Function Tests', 600, 'Blood', '24 hours'],
  ['t-bile-acid', 'BILE ACID', 'Liver Function Tests', 1500, 'Blood', '24 hours'],
  ['t-bilirubin-total-direct', 'BILIRUBIN (TOTAL AND DIRECT)', 'Liver Function Tests', 300, 'Blood', '24 hours'],
  ['t-bilirubin-direct', 'BILIRUBIN DIRECT', 'Liver Function Tests', 86, 'Blood', '24 hours'],
  ['t-bilirubin-total', 'BILIRUBIN TOTAL', 'Liver Function Tests', 238, 'Blood', '24 hours'],
  ['t-biofire-resp', 'Biofire Respiratory Panel', 'COVID & Viral Tests', 22000, 'Nasal Swab', '24 hours'],
  ['t-blood-culture-both', 'BLOOD CULTURE (AEROBIC and ANAEROBIC)', 'Culture & Microbiology', 700, 'Blood', '48 hours'],
  ['t-blood-culture-aer', 'BLOOD CULTURE (AEROBIC)', 'Culture & Microbiology', 1140, 'Blood', '48 hours'],
  ['t-blood-culture-anaer', 'BLOOD CULTURE (ANAEROBIC)', 'Culture & Microbiology', 600, 'Blood', '48 hours'],
  ['t-blood-group', 'BLOOD GROUP', 'Blood Tests', 200, 'Blood', '12 hours'],
  ['t-body-fluid-ldh', 'BODY FLUID / CSF LDH', 'Miscellaneous Tests', 475, 'CSF/Fluid', '24 hours'],
  ['t-body-fluid-chloride', 'BODY FLUID CHLORIDE', 'Miscellaneous Tests', 190, 'Fluid', '24 hours'],
  ['t-body-fluid-exam', 'BODY FLUID EXAMINATION', 'Miscellaneous Tests', 475, 'Fluid', '24 hours'],
  ['t-body-fluid-pcv', 'BODY FLUID PCV', 'Miscellaneous Tests', 142, 'Fluid', '24 hours'],
  ['t-boh-profile', 'BOH PROFILE', 'Pregnancy Tests', 11000, 'Blood', '48 hours'],
  ['t-bone-profile', 'BONE PROFILE', 'Miscellaneous Tests', 1568, 'Blood', '24 hours'],

  // Page 4
  ['t-brucella-igg', 'BRUCELLA ANTIBODY IgG', 'Infection & Fever Tests', 1615, 'Blood', '24 hours'],
  ['t-brucella-igm', 'BRUCELLA ANTIBODY IgM', 'Infection & Fever Tests', 1615, 'Blood', '24 hours'],
  ['t-bt-ct', 'BT CT', 'Blood Tests', 200, 'Blood', '12 hours'],
  ['t-bun', 'BUN (BLOOD UREA NITROGEN)', 'Kidney Function Tests', 190, 'Blood', '24 hours'],
  ['t-crp-quant-large', 'C - REACTIVE PROTEIN(CRP) QUANTITATIVE', 'Infection & Fever Tests', 500, 'Blood', '12 hours'],
  ['t-c-anca', 'C-ANCA', 'Autoimmune Tests', 1450, 'Blood', '24 hours'],
  ['t-c-peptide', 'C-PEPTIDE (FASTING)', 'Diabetes Tests', 1000, 'Blood', '24 hours'],
  ['t-cpk', 'C.P.K.', 'Cardiac Tests', 400, 'Blood', '24 hours'],
  ['t-cpk-mb', 'C.P.K.-MB', 'Cardiac Tests', 760, 'Blood', '24 hours'],
  ['t-crp-qual', 'C.R.P. (QUALITATIVE)', 'Infection & Fever Tests', 500, 'Blood', '12 hours'],
  ['t-crp-quant', 'C.R.P. (QUANTITATIVE)', 'Infection & Fever Tests', 500, 'Blood', '12 hours'],
  ['t-c3', 'C3 (COMPLEMENT-3)', 'Autoimmune Tests', 800, 'Blood', '24 hours'],
  ['t-c4', 'C4 (COMPLEMENT-4)', 'Autoimmune Tests', 800, 'Blood', '24 hours'],
  ['t-ca125', 'CA 125', 'Cancer Marker Tests', 1400, 'Blood', '24 hours'],
  ['t-ca153', 'CA 15.3', 'Cancer Marker Tests', 1450, 'Blood', '24 hours'],
  ['t-ca724', 'CA 72.4', 'Cancer Marker Tests', 1850, 'Blood', '24 hours'],
  ['t-calcium', 'CALCIUM', 'Kidney Function Tests', 200, 'Blood', '24 hours'],
  ['t-calcium-phosphate', 'CALCIUM PHOSPHATE', 'Kidney Function Tests', 350, 'Blood', '24 hours'],
  ['t-calcium-spot-urine', 'Calcium Spot Urine', 'Urine Tests', 200, 'Urine', '24 hours'],
  ['t-cancer-screening', 'CANCER SCREENING', 'Cancer Marker Tests', 3500, 'Blood', '24 hours'],
  ['t-carbamazepine', 'CARBAMAZEPINE', 'Miscellaneous Tests', 1000, 'Blood', '24 hours'],
  ['t-ca199', 'CARBOHYDRATE ANTIGEN CA 19-9', 'Cancer Marker Tests', 1400, 'Blood', '24 hours'],
  ['t-cea', 'CARCINO EMBRYONIC ANTIGEN (CEA)', 'Cancer Marker Tests', 700, 'Blood', '24 hours'],
  ['t-cardiac-marker', 'Cardiac Marker', 'Cardiac Tests', 3500, 'Blood', '12 hours'],
  ['t-ceruloplasmin', 'CERULOPLASMIN', 'Liver Function Tests', 1200, 'Blood', '24 hours'],
  ['t-chest-pa', 'CHEST PA', 'Imaging & Other Diagnostics', 600, 'Not Required', '12 hours'],
  ['t-chikungunya', 'CHIKUNGUNYA IgG IgM', 'Infection & Fever Tests', 900, 'Blood', '24 hours'],
  ['t-chloride', 'CHLORIDE', 'Kidney Function Tests', 238, 'Blood', '24 hours'],

  // Page 5
  ['t-cholesterol', 'CHOLESTEROL', 'Cardiac Tests', 150, 'Blood', '24 hours'],
  ['t-cholinesterase', 'CHOLINESTERASE', 'Liver Function Tests', 760, 'Blood', '24 hours'],
  ['t-coagulation-profile', 'COAGULATION PROFILE', 'Blood Tests', 1800, 'Blood', '24 hours'],
  ['t-cbc-routine', 'COMPLETE BLOOD COUNT', 'Blood Tests', 250, 'Blood', '12 hours'],
  ['t-cortisol-4pm', 'CORTISOL 4 P.M.', 'Hormone Tests', 750, 'Blood', '24 hours'],
  ['t-cortisol-8am', 'CORTISOL 8 A.M.', 'Hormone Tests', 750, 'Blood', '24 hours'],
  ['t-covid-igg-elisa', 'COVID ANTIBODY IgG-ELISA', 'COVID & Viral Tests', 500, 'Blood', '24 hours'],
  ['t-covid-antigen', 'Covid Antigen', 'COVID & Viral Tests', 500, 'Nasal Swab', '12 hours'],
  ['t-cpk-raw', 'CREATINE PHOSPHOKINASE (CPK)', 'Cardiac Tests', 400, 'Blood', '24 hours'],
  ['t-cpk-and-cpk-mb', 'CREATINE PHOSPHOKINASE and CREATINE PHOSPHOKINASE-MB', 'Cardiac Tests', 1050, 'Blood', '24 hours'],
  ['t-cpk-nac', 'CREATINE PHOSPHOKINASE NAC', 'Cardiac Tests', 285, 'Blood', '24 hours'],
  ['t-cpk-mb-only', 'CREATINE PHOSPHOKINASE-MB (CPK-MB)', 'Cardiac Tests', 650, 'Blood', '24 hours'],
  ['t-cpk-mm-bb', 'CREATINE PHOSPHOKINASE-MM/BB', 'Cardiac Tests', 522, 'Blood', '24 hours'],
  ['t-creatinine', 'CREATININE', 'Kidney Function Tests', 150, 'Blood', '12 hours'],
  ['t-csf-routine', 'CSF FLUID ROUTINE EXAMINATION', 'Miscellaneous Tests', 475, 'CSF Fluid', '24 hours'],
  ['t-culture-test', 'CULTURE AND SENSITIVITY TEST (BLOOD/FLUID/TISSUE/PUS/SPUTUM/URINE))', 'Culture & Microbiology', 700, 'Swab/Fluid/Urine', '48 hours'],
  ['t-fnac', 'Cytology-FNAC', 'Cancer Marker Tests', 855, 'Aspirate', '48 hours'],
  ['t-pap-cytology', 'Cytology-PAP', 'Cancer Marker Tests', 570, 'Cervical Swab', '48 hours'],
  ['t-d-dimer', 'D-DIMER', 'Cardiac Tests', 1400, 'Blood', '12 hours'],
  ['t-dc', 'DC', 'Blood Tests', 38, 'Blood', '12 hours'],
  ['t-dhea', 'DEHYDROEPIANDROSTERONE (DHEA)', 'Hormone Tests', 570, 'Blood', '24 hours'],
  ['t-dengue-rapid', 'DENGUE (RAPID)', 'Infection & Fever Tests', 1800, 'Blood', '12 hours'],
  ['t-dengue-igg', 'DENGUE IgG', 'Infection & Fever Tests', 600, 'Blood', '12 hours'],
  ['t-dengue-igg-elisa', 'DENGUE IgG ANTIBORY (ELISA)', 'Infection & Fever Tests', 600, 'Blood', '24 hours'],
  ['t-dengue-igm', 'DENGUE IgM', 'Infection & Fever Tests', 600, 'Blood', '12 hours'],
  ['t-dengue-igm-duplicate', 'Dengue IGM', 'Infection & Fever Tests', 600, 'Blood', '12 hours'],
  ['t-dengue-igm-elisa', 'DENGUE IgM ANTIBODY (ELISA)', 'Infection & Fever Tests', 600, 'Blood', '24 hours'],
  ['t-dengue-ns1', 'DENGUE NS1 ANTIGEN', 'Infection & Fever Tests', 600, 'Blood', '12 hours'],

  // Page 6
  ['t-dengue-ns1-elisa', 'Dengue NS1 Antigen by ELISA', 'Infection & Fever Tests', 600, 'Blood', '24 hours'],
  ['t-dengue-pcr', 'DENGUE PCR VIRAL LOAD', 'COVID & Viral Tests', 1900, 'Blood', '24 hours'],
  ['t-dht', 'Dihydrotestosterone', 'Hormone Tests', 1800, 'Blood', '24 hours'],
  ['t-dct', 'DIRECT COOMBS TEST (DCT)', 'Blood Tests', 650, 'Blood', '24 hours'],
  ['t-double-marker', 'DOUBLE MARKER (PREGNANCY)', 'Pregnancy Tests', 2450, 'Blood', '24 hours'],
  ['t-e2-prog-fsh-lh', 'E2, PROGESTERON,FSH, LH', 'Hormone Tests', 2270, 'Blood', '24 hours'],
  ['t-ebv-vcm-igm', 'EBV VCM IGM', 'COVID & Viral Tests', 3500, 'Blood', '24 hours'],
  ['t-ecg', 'ECG', 'Imaging & Other Diagnostics', 500, 'Not Required', '12 hours'],
  ['t-electrolytes', 'ELECTROLYTES (NA ,K , CL-)', 'Kidney Function Tests', 500, 'Blood', '12 hours'],
  ['t-esr', 'ESR (ERYTHROCYTE SEDIMENTATION RATE)', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-egfr', 'ESTIMATED GLOMERULO FILTRATION RATE (eGFR)', 'Kidney Function Tests', 250, 'Blood', '12 hours'],
  ['t-estradiol', 'ESTRADIOL / OESTROGEN / E2', 'Hormone Tests', 550, 'Blood', '24 hours'],
  ['t-fecal-calprotectin', 'Fecal Calprotactin', 'Stool Tests', 3800, 'Stool', '24 hours'],
  ['t-ferritin', 'FERRITIN', 'Blood Tests', 550, 'Blood', '24 hours'],
  ['t-fdp', 'FIBRIN DEGRADATION PRODUCT (FDP)', 'Blood Tests', 900, 'Blood', '24 hours'],
  ['t-fibrinogen', 'FIBRINOGEN', 'Blood Tests', 475, 'Blood', '24 hours'],
  ['t-filaria-rapid', 'FILARIA ANTIGEN CARD (RAPID)', 'Infection & Fever Tests', 380, 'Blood', '12 hours'],
  ['t-fitness-cert', 'FITNESS CERTICATE', 'Miscellaneous Tests', 1000, 'Not Required', '24 hours'],
  ['t-fta-abs', 'FLUORESCENCE TREPONERNAL ANTIBODIES (FTA-ABS), IGG/IGM', 'Infection & Fever Tests', 1900, 'Blood', '24 hours'],
  ['t-folate', 'FOLATE / FOLIC ACID', 'Vitamin Tests', 1250, 'Blood', '24 hours'],
  ['t-fsh', 'FOLLICLE STIMULATING HORMONE (FSH)', 'Hormone Tests', 400, 'Blood', '24 hours'],
  ['t-free-beta-hcg', 'FREE BETA HCG', 'Pregnancy Tests', 1200, 'Blood', '24 hours'],
  ['t-free-lambda', 'FREE LAMBDA FREELITE CHAINS SERUM', 'Cancer Marker Tests', 2990, 'Blood', '48 hours'],
  ['t-free-psa', 'FREE PSA', 'Cancer Marker Tests', 850, 'Blood', '24 hours'],
  ['t-free-t3', 'FREE T3 (FT3)', 'Thyroid Tests', 250, 'Blood', '12 hours'],
  ['t-free-t3-t4-tsh', 'FREE T3, FREE T4, TSH', 'Thyroid Tests', 550, 'Blood', '12 hours'],
  ['t-free-t4', 'FREE T4 (FT4)', 'Thyroid Tests', 250, 'Blood', '12 hours'],
  ['t-fructosamine', 'FRUCTOSAMINE', 'Diabetes Tests', 950, 'Blood', '24 hours'],

  // Page 7
  ['t-fsh-lh-prol-tsh', 'FSH LH PROLACTIN TSH', 'Hormone Tests', 1100, 'Blood', '24 hours'],
  ['t-g6pd', 'G6PD QUANTITATIVE', 'Blood Tests', 750, 'Blood', '24 hours'],
  ['t-ggt', 'GAMMA GT (GGT)', 'Liver Function Tests', 120, 'Blood', '24 hours'],
  ['t-globulin', 'GLOBULIN', 'Blood Tests', 200, 'Blood', '24 hours'],
  ['t-glucose-1hr', 'GLUCOSE LEVEL (1ST HOUR)', 'Diabetes Tests', 60, 'Blood', '12 hours'],
  ['t-gtt', 'GLUCOSE TOLERANCE TEST (GTT)', 'Diabetes Tests', 120, 'Blood', '12 hours'],
  ['t-gtt-5samples', 'GLUCOSE TOLERANCE TEST (GTT) (5 SAMPLES)', 'Diabetes Tests', 300, 'Blood', '12 hours'],
  ['t-gtt-3samples', 'GLUCOSE TOLERANCE TEST (GTT) 3 SMAPLES', 'Diabetes Tests', 180, 'Blood', '12 hours'],
  ['t-glucose-fasting', 'GLUCOSE, FASTING (FBS)', 'Diabetes Tests', 60, 'Blood', '12 hours'],
  ['t-glucose-pp', 'GLUCOSE, POST PRANDIAL (PPBS), 2 HOURS', 'Diabetes Tests', 60, 'Blood', '12 hours'],
  ['t-glucose-random', 'GLUCOSE, RANDOM (RBS)', 'Diabetes Tests', 60, 'Blood', '12 hours'],
  ['t-hba1c-standard', 'GLYCOSYLATED HAEMOGLOBIN (HbA1C)', 'Diabetes Tests', 450, 'Blood', '12 hours'],
  ['t-hba1c-hplc', 'GLYCOSYLATED HAEMOGLOBIN HBA1C (HPLC)', 'Diabetes Tests', 500, 'Blood', '12 hours'],
  ['t-gram-stain', 'GRAM STAIN - ANY FLUID', 'Culture & Microbiology', 400, 'Fluid/Swab', '24 hours'],
  ['t-h1n1', 'H1N1', 'COVID & Viral Tests', 3500, 'Nasal Swab', '24 hours'],
  ['t-h2n3', 'H2N3', 'COVID & Viral Tests', 3500, 'Nasal Swab', '24 hours'],
  ['t-haemoglobin-hb', 'HAEMOGLOBIN (HB)', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-hb-electrophoresis', 'HB-ELECTROPHORESIS (HPLC)', 'Blood Tests', 800, 'Blood', '24 hours'],
  ['t-hbsag-rapid', 'HBsAg Rapid', 'Infection & Fever Tests', 450, 'Blood', '12 hours'],
  ['t-hcv-rapid', 'HCV Rapid', 'Infection & Fever Tests', 700, 'Blood', '12 hours'],
  ['t-hdl-chol', 'HDL-CHOLESTEROL', 'Cardiac Tests', 200, 'Blood', '12 hours'],
  ['t-h-pylori-ab', 'HELICOBACTER PYLORI IgG / IgM / IgA EACH', 'Infection & Fever Tests', 2200, 'Blood', '24 hours'],
  ['t-hemoglobin-only', 'HEMOGLOBIN', 'Blood Tests', 200, 'Blood', '12 hours'],
  ['t-hbv-dna-pcr', 'HEPATITIS B (HBV-DNA) QUANTITATIVE, REAL TIME PCR', 'Infection & Fever Tests', 3500, 'Blood', '48 hours'],
  ['t-hbcag', 'HEPATITIS B CORE ANTIGEN (HBCAg)', 'Infection & Fever Tests', 1000, 'Blood', '24 hours'],
  ['t-hbeag', 'HEPATITIS B e ANTIGEN (HBeAg)', 'Infection & Fever Tests', 1000, 'Blood', '24 hours'],
  ['t-histopathology', 'HISTOPATHOLOGY', 'Miscellaneous Tests', 1000, 'Biopsy Tissue', '48 hours'],
  ['t-hiv-rapid', 'HIV - I and II Rapid', 'COVID & Viral Tests', 350, 'Blood', '12 hours'],

  // Page 8
  ['t-hla-b27', 'HLA B-27', 'Autoimmune Tests', 1200, 'Blood', '24 hours'],
  ['t-hla-b27-pcr', 'HLA B27 PCR METHOD', 'Autoimmune Tests', 1800, 'Blood', '24 hours'],
  ['t-homa-ir', 'HOMA-IR SCORE (Fatty Liver)', 'Diabetes Tests', 600, 'Blood', '24 hours'],
  ['t-homocysteine', 'HOMOCYSTEINE (Serum)', 'Cardiac Tests', 1200, 'Blood', '24 hours'],
  ['t-hs-trop-t', 'HS TROP-T', 'Cardiac Tests', 1500, 'Blood', '12 hours'],
  ['t-hs-crp', 'HS-CRP', 'Cardiac Tests', 550, 'Blood', '12 hours'],
  ['t-ict', 'INDIRECT COOMBS TEST (ICT)', 'Blood Tests', 650, 'Blood', '24 hours'],
  ['t-inorganic-phosphorus', 'INORGANIC PHOSPHORUS', 'Kidney Function Tests', 200, 'Blood', '24 hours'],
  ['t-insulin-fasting', 'INSULIN (FASTING)', 'Diabetes Tests', 600, 'Blood', '24 hours'],
  ['t-insulin-random', 'INSULIN (RANDOM)', 'Diabetes Tests', 600, 'Blood', '24 hours'],
  ['t-ipth', 'INTACT PARATHYROID HORMONE (iPTH)', 'Hormone Tests', 1000, 'Blood', '24 hours'],
  ['t-il6', 'INTERLEUKIN 6 (IL 6)', 'Infection & Fever Tests', 3000, 'Blood', '24 hours'],
  ['t-ionized-calcium', 'IONIZED CALCIUM', 'Kidney Function Tests', 450, 'Blood', '24 hours'],
  ['t-iron', 'IRON', 'Blood Tests', 450, 'Blood', '24 hours'],
  ['t-iron-studies', 'IRON STUDIES', 'Blood Tests', 700, 'Blood', '24 hours'],
  ['t-karyotyping', 'KARYOTYPING - BLOOD', 'Miscellaneous Tests', 4000, 'Blood', '48 hours'],
  ['t-kft-panel', 'KIDNEY FUNCTION TEST (KFT)', 'Kidney Function Tests', 800, 'Blood', '24 hours'],
  ['t-ldh', 'LACTATE DEHYDROGENOUS (LDH)', 'Miscellaneous Tests', 400, 'Blood', '24 hours'],
  ['t-ldl-chol', 'LDL-CHOLESTEROL', 'Cardiac Tests', 200, 'Blood', '12 hours'],
  ['t-leptospira-igm', 'Leptospira IgM antibodies by EIA - Serum', 'Infection & Fever Tests', 900, 'Blood', '24 hours'],
  ['t-lipase', 'LIPASE', 'Miscellaneous Tests', 400, 'Blood', '24 hours'],
  ['t-lipid-panel', 'LIPID PROFILE', 'Cardiac Tests', 450, 'Blood', '12 hours'],
  ['t-lithium', 'LITHIUM', 'Miscellaneous Tests', 400, 'Blood', '24 hours'],
  ['t-lft-panel', 'LIVER PROFILE (LFT)', 'Liver Function Tests', 500, 'Blood', '12 hours'],
  ['t-lh', 'LUTEINIZING HORMONE (LH)', 'Hormone Tests', 400, 'Blood', '24 hours'],
  ['t-magnesium', 'MAGNESIUM', 'Kidney Function Tests', 450, 'Blood', '24 hours'],
  ['t-malaria-antigen', 'MALARIA ANTIGEN DETECTION (VIVAX and FALCIPARUM)', 'Infection & Fever Tests', 400, 'Blood', '12 hours'],
  ['t-malaria-parasite', 'MALARIA PARASITE (MP)', 'Infection & Fever Tests', 200, 'Blood', '12 hours'],

  // Page 9
  ['t-mantoux', 'MANTOUX TEST (Tuberculin Skin Test)', 'Infection & Fever Tests', 250, 'Intradermal', '48 hours'],
  ['t-mantoux-tu', 'MONTOUX TESTS 10TU or 5TU', 'Infection & Fever Tests', 200, 'Intradermal', '48 hours'],
  ['t-mcv', 'MCV', 'Blood Tests', 150, 'Blood', '12 hours'],
  ['t-mp-antigen', 'MP Antigen', 'Infection & Fever Tests', 400, 'Blood', '12 hours'],
  ['t-mt', 'MT', 'Infection & Fever Tests', 300, 'Blood', '12 hours'],
  ['t-nt-probnp', 'NT- Pro BNP', 'Cardiac Tests', 2000, 'Blood', '24 hours'],
  ['t-ogct', 'OGCT', 'Diabetes Tests', 200, 'Blood', '12 hours'],
  ['t-p-anca', 'P-ANCA', 'Autoimmune Tests', 1400, 'Blood', '24 hours'],
  ['t-pcv', 'PACKED CELL VOLUME', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-pap-liquid', 'PAP SMEAR - Liquid Based', 'Cancer Marker Tests', 1200, 'Cervical Swab', '48 hours'],
  ['t-papp-a', 'PAPP - A', 'Pregnancy Tests', 1000, 'Blood', '24 hours'],
  ['t-pcv-platelets', 'PCV and PLATELET COUNT', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-peripheral-smear', 'PERIPHERAL BLOOD SMEAR EXAMINATION (PS)', 'Blood Tests', 350, 'Blood', '24 hours'],
  ['t-pft', 'PFT', 'Imaging & Other Diagnostics', 1500, 'Not Required', '12 hours'],
  ['t-platelets', 'PLATELET COUNT', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-pleural-routine', 'Pleural Fluid Routine Micro.', 'Miscellaneous Tests', 700, 'Pleural Fluid', '24 hours'],
  ['t-pleural-ada', 'Plueral Fluid Ada', 'Miscellaneous Tests', 1000, 'Pleural Fluid', '24 hours'],
  ['t-potassium', 'POTASSIUM (K )', 'Kidney Function Tests', 250, 'Blood', '12 hours'],
  ['t-preoperative-eye', 'Preoperative Profile (Eye Hospital)', 'Miscellaneous Tests', 2550, 'Blood/Urine', '24 hours'],
  ['t-procalcitonin', 'PROCALCITONIN (PCT)', 'Infection & Fever Tests', 2700, 'Blood', '24 hours'],
  ['t-prolactin', 'PROLACTIN', 'Hormone Tests', 580, 'Blood', '24 hours'],
  ['t-psa', 'PROSTATE SPECIFIC ANTIGEN (PSA)', 'Cancer Marker Tests', 800, 'Blood', '24 hours'],
  ['t-protein-c', 'Protein C', 'Blood Tests', 4500, 'Blood', '48 hours'],
  ['t-protein-electrophoresis', 'protein electrophoresis', 'Blood Tests', 800, 'Blood', '48 hours'],
  ['t-protein-s', 'Protein S', 'Blood Tests', 5000, 'Blood', '48 hours'],
  ['t-pt', 'PROTHROMBIN TIME (PT)', 'Blood Tests', 400, 'Blood', '12 hours'],
  ['t-prp', 'PRP', 'Blood Tests', 300, 'Blood', '24 hours'],
  ['t-pus-culture', 'PUS CULTURE AND SENSITIVITY', 'Culture & Microbiology', 900, 'Pus Swab', '48 hours'],
  ['t-quadruple-marker', 'QUADRUPLE MARKER TEST', 'Pregnancy Tests', 3850, 'Blood', '24 hours'],

  // Page 10
  ['t-ra-qual', 'RA FACTOR (QUALITATIVE)', 'Autoimmune Tests', 238, 'Blood', '12 hours'],
  ['t-ra-quant', 'RA FACTOR (QUANTITATIVE)', 'Autoimmune Tests', 500, 'Blood', '24 hours'],
  ['t-rbc-count', 'RBC COUNT', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-rft-panel', 'RENAL FUNCTION TEST (RFT)', 'Kidney Function Tests', 700, 'Blood', '24 hours'],
  ['t-reticulocyte', 'RETICULOCYTE COUNT', 'Blood Tests', 200, 'Blood', '12 hours'],
  ['t-rubella-igg', 'RUBELLA IgG', 'Pregnancy Tests', 570, 'Blood', '24 hours'],
  ['t-rubella-igm', 'RUBELLA IgM', 'Pregnancy Tests', 570, 'Blood', '24 hours'],
  ['t-rubella-igg-igm', 'RUBELLA VIRUS IgG and IgM', 'Pregnancy Tests', 1400, 'Blood', '24 hours'],
  ['t-saag', 'SAAG RATIO', 'Liver Function Tests', 550, 'Ascitic Fluid', '24 hours'],
  ['t-salmonella-igm', 'salmonella typhi IGM', 'Infection & Fever Tests', 600, 'Blood', '12 hours'],
  ['t-covid-pcr', 'SARS CoV -2 REAL TIME PCR (COVID-19)', 'COVID & Viral Tests', 700, 'Nasal Swab', '12 hours'],
  ['t-scrub-typhus', 'SCRUB TYPHUS', 'Infection & Fever Tests', 1100, 'Blood', '24 hours'],
  ['t-semen-analysis', 'SEMEN ANALYSIS', 'Miscellaneous Tests', 600, 'Semen', '24 hours'],
  ['t-iga', 'SERUM IMMUNOGLOBULIN IgA', 'Autoimmune Tests', 900, 'Blood', '24 hours'],
  ['t-igg', 'SERUM IMMUNOGLOBULIN IgG', 'Autoimmune Tests', 900, 'Blood', '24 hours'],
  ['t-igg-igm-iga', 'SERUM IMMUNOGLOBULIN IgG IgM IgA', 'Autoimmune Tests', 2700, 'Blood', '24 hours'],
  ['t-igm', 'SERUM IMMUNOGLOBULIN IgM', 'Autoimmune Tests', 900, 'Blood', '24 hours'],
  ['t-ige', 'SERUM TOTAL IgE', 'Allergy Tests', 600, 'Blood', '24 hours'],
  ['t-sgot', 'SGOT (AST)', 'Liver Function Tests', 150, 'Blood', '12 hours'],
  ['t-sgpt', 'SGPT (ALT)', 'Liver Function Tests', 150, 'Blood', '12 hours'],
  ['t-sickling', 'SICKLING TEST', 'Blood Tests', 700, 'Blood', '24 hours'],
  ['t-sm-rnp', 'SM/RNP (ELISA)', 'Autoimmune Tests', 1500, 'Blood', '24 hours'],
  ['t-sodium', 'SODIUM (NA )', 'Kidney Function Tests', 238, 'Blood', '12 hours'],
  ['t-sodium-potassium', 'SODIUM AND POTASSIUM', 'Kidney Function Tests', 400, 'Blood', '12 hours'],
  ['t-spot-acr', 'SPOT URINE ALBUMIN AND CREATININE RATIO(ACR)', 'Urine Tests', 600, 'Urine', '24 hours'],
  ['t-sputum-afb', 'SPUTUM FOR AFB', 'Culture & Microbiology', 350, 'Sputum', '24 hours'],
  ['t-sputum-genexpert', 'SPUTUM FOR GENEXPART', 'Culture & Microbiology', 2700, 'Sputum', '24 hours'],
  ['t-sputum-routine', 'SPUTUM FOR ROUTINE EXAMINATION', 'Culture & Microbiology', 800, 'Sputum', '24 hours'],

  // Page 11
  ['t-stool-hanging-drop', 'STOOL EXAMINATION, HANGING DROP PREPARATION', 'Stool Tests', 200, 'Stool', '24 hours'],
  ['t-stool-culture', 'STOOL FOR CULTURE AND SENSITIVITY', 'Stool Tests', 900, 'Stool', '48 hours'],
  ['t-stool-obt', 'STOOL FOR OCCULT BLOOD TEST(OBT)', 'Stool Tests', 100, 'Stool', '24 hours'],
  ['t-stool-routine', 'STOOL FOR ROUTINE EXAMINATION (Stool R/M)', 'Stool Tests', 200, 'Stool', '24 hours'],
  ['t-t3-t4-tsh', 'T3 T4 TSH', 'Thyroid Tests', 450, 'Blood', '12 hours'],
  ['t-tb-gold', 'TB GOLD', 'Infection & Fever Tests', 2400, 'Blood', '48 hours'],
  ['t-testosterone-free', 'TESTOSTERONE (Free)', 'Hormone Tests', 1800, 'Blood', '24 hours'],
  ['t-testosterone-total', 'TESTOSTERONE (Total)', 'Hormone Tests', 700, 'Blood', '24 hours'],
  ['t-thalassemia-profile', 'THALASSEMIA PROFILE', 'Blood Tests', 3300, 'Blood', '24 hours'],
  ['t-thalassemia-screen', 'Thalassemia screen', 'Blood Tests', 1350, 'Blood', '24 hours'],
  ['t-tft', 'THYROID FUNCTION TEST (TFT)', 'Thyroid Tests', 450, 'Blood', '12 hours'],
  ['t-tsh', 'THYROID STIMULATING HORMONE (TSH)', 'Thyroid Tests', 250, 'Blood', '12 hours'],
  ['t-t4', 'THYROXINE (T4)', 'Thyroid Tests', 200, 'Blood', '12 hours'],
  ['t-ttg-iga-antibodies', 'TISSUE TRANSGLUTAMINASE (tTG)-IgA ANTIBODIES', 'Autoimmune Tests', 1300, 'Blood', '24 hours'],
  ['t-torch-igg', 'TORCH IGG', 'Pregnancy Tests', 1500, 'Blood', '24 hours'],
  ['t-torch-igm', 'TORCH IGM', 'Pregnancy Tests', 1500, 'Blood', '24 hours'],
  ['t-eosinophils', 'Total Eosinophils Count', 'Blood Tests', 250, 'Blood', '12 hours'],
  ['t-tibc', 'TOTAL IRON-BINDING CAPACITY (TIBC)', 'Blood Tests', 440, 'Blood', '24 hours'],
  ['t-tlc', 'TOTAL LEUCOCYTE COUNT (TLC)', 'Blood Tests', 100, 'Blood', '12 hours'],
  ['t-total-protein', 'TOTAL PROTEIN', 'Liver Function Tests', 200, 'Blood', '12 hours'],
  ['t-toxoplasma-igg', 'TOXOPLASMA IgG', 'Pregnancy Tests', 700, 'Blood', '24 hours'],
  ['t-toxoplasma-igg-igm', 'TOXOPLASMA IgG IgM', 'Pregnancy Tests', 1400, 'Blood', '24 hours'],
  ['t-toxoplasma-igm', 'TOXOPLASMA IgM', 'Pregnancy Tests', 700, 'Blood', '24 hours'],
  ['t-transferrin', 'TRANSFERRIN', 'Blood Tests', 1000, 'Blood', '24 hours'],
  ['t-triglyceride', 'TRIGLYCERIDE', 'Cardiac Tests', 200, 'Blood', '12 hours'],
  ['t-t3', 'TRIIODOTHYRONINE (T3)', 'Thyroid Tests', 200, 'Blood', '12 hours'],
  ['t-triple-marker', 'Triple Marker', 'Pregnancy Tests', 2400, 'Blood', '24 hours'],
  ['t-troponin-t', 'Tropinine T', 'Cardiac Tests', 2000, 'Blood', '12 hours'],

  // Page 12
  ['t-troponin-i', 'TROPONIN - I', 'Cardiac Tests', 1800, 'Blood', '12 hours'],
  ['t-tumor-marker', 'Tumor Marker', 'Cancer Marker Tests', 5500, 'Blood', '48 hours'],
  ['t-typhidot', 'TYPHIDOT (IgG and IgM)', 'Infection & Fever Tests', 500, 'Blood', '12 hours'],
  ['t-ultra-tsh', 'ULTRA SENSITIVE TSH', 'Thyroid Tests', 250, 'Blood', '12 hours'],
  ['t-urea', 'UREA', 'Kidney Function Tests', 150, 'Blood', '12 hours'],
  ['t-uric-acid', 'URIC ACID', 'Kidney Function Tests', 150, 'Blood', '12 hours'],
  ['t-urine-protein-creat-ratio', 'Urinary protein creatinine ratio', 'Urine Tests', 550, 'Urine', '24 hours'],
  ['t-urine-culture', 'URINE CULTURE AND SENSIVITY', 'Urine Tests', 900, 'Urine', '48 hours'],
  ['t-urine-acr', 'URINE FOR ALBUMIN CREATININE RATIO', 'Urine Tests', 700, 'Urine', '24 hours'],
  ['t-urine-bile', 'URINE FOR BILE SALT AND BILE PIGMENT', 'Urine Tests', 66, 'Urine', '24 hours']
];

export const routineTests: Test[] = rawTests.map(([id, name, category, price, specimen, reportTime]) => {
  return {
    id,
    name,
    category,
    price,
    originalPrice: Math.round(price * 2.2),
    specimen: specimen || 'Blood',
    reportTime: reportTime || '24 hours',
    description: `Official pathology test for ${name} from our accredited diagnostics catalog.`
  };
});
